[project]
name = "storage-service"
version = "1.0.0"
description = "Storage service for chat application"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.104.1",
    "uvicorn>=0.24.0",
    "sqlalchemy>=2.0.23",
    "python-dotenv>=1.0.0",
    "pydantic>=2.5.0",
]
